#!/bin/sh

echo "you have to run \"fish ./2cleaningUp.sh\""
set folderName "tempf"
set folderName (ls |grep -v .sh | grep -v .md | grep -v myAtCoder | grep -v archives | grep -v go.mod | grep -v main.go )

mv ./main.go ./$folderName/lastMain.go
mv ./$folderName/ ./archives/
rm ./myAtCoder
cp ./archives/baseCode.go ./main.go

echo -n ---; echo " ~/check.sh"

~/check.sh

echo ---


git add ./archives/*
git commit -m "$folderName の追加"
git push
